# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Blithfield Construction
email: Antbagnall68@gmail.com
description: > # this means to ignore newlines until "baseurl:"
Blithfield Construction is a well establishedconstruction firm established in 1972,
based in Staffordshire, specialising in all aspects of groundworks ranging from [
excavation to the finished surface.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: Blithfieldconstruction
github_username:  Bagnallscience

# Build settings
markdown: kramdown
